//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorimeterUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public string Category { get; set; }
        public string ProductName { get; set; }
        public decimal Calories { get; set; }
        public Nullable<decimal> Fat { get; set; }
        public Nullable<decimal> Carbohydrates { get; set; }
        public Nullable<decimal> Proteins { get; set; }
    }
}
